spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      connect-timeout: 3000ms
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

  cache:
    type: redis
    cache-names: user,userList,file,fileList,hotData,statistics
    redis:
      time-to-live: 1800000
      cache-null-values: false
      key-prefix: "cache:"
      use-key-prefix: true

cache:
  hot-data-threshold: 10
  hot-data-window: 60
  ttl:
    default: 3600
    user: 7200
    file: 1800
    list: 600