# 主配置文件
# 文件路径: src/main/resources/application.yml

spring:
  application:
    name: project

  # 激活其他配置文件
  profiles:
    active: datasource,redis

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 3159140248@qq.com
    password: qwagadoukdvndcce
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  # 线程池配置
  task:
    execution:
      pool:
        core-size: 8
        max-size: 10
        queue-capacity: 25

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  # ⚠️ 注意：数据源配置已移到 application-datasource.yml
  # 这里不再配置 spring.datasource，避免与动态数据源冲突

  # 安全认证（基础配置，实际使用JWT）
  security:
    user:
      name: user
      password: 123456

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 1s
    template:
      mandatory: true
      retry:
        enabled: true
        multiplier: 1
        max-attempts: 3
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 1
    virtual-host: "/"

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false  # 生产环境建议关闭SQL打印
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
          fetch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: false  # 生产环境建议关闭

# 服务器配置
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  address: 0.0.0.0
  port: 9090

# Swagger/Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-doc
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.mi.project.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

# 统一的日志配置（合并了三个文件的日志配置）
logging:
  level:
    # 项目日志
    com.mi.project: DEBUG
    com.mi.project.config.datasource: DEBUG  # 数据源切换日志
    com.mi.project.cache: DEBUG              # 缓存日志
    
    # Spring框架日志
    org.springframework.cache: DEBUG         # Spring缓存日志
    org.springframework.data.redis: DEBUG    # Redis日志
    org.springframework.jdbc: DEBUG          # JDBC日志
    org.springframework.amqp: INFO           # RabbitMQ日志
    
    # 数据库相关日志
    com.zaxxer.hikari: DEBUG                 # 连接池日志
    org.hibernate: WARN                      # Hibernate日志（过多，设为WARN）
    org.hibernate.SQL: DEBUG                 # SQL语句（可选）
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL参数（可选）

  # 日志格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  # 日志文件
  file:
    name: logs/point-data-processor.log
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 100MB

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true