# Redis缓存配置
# 文件路径: src/main/resources/application-redis.yml

spring:
  data:
    redis:
      # Redis服务器地址
      host: localhost
      # Redis服务器端口
      port: 6379
      # Redis数据库索引(默认为0)
      database: 0
      # Redis密码(如果有的话)
      password:
      # 连接超时时间
      connect-timeout: 3000ms
      # 命令执行超时时间
      timeout: 3000ms

      # Lettuce客户端配置
      lettuce:
        pool:
          # 连接池最大连接数(负数表示没有限制)
          max-active: 20
          # 连接池最大阻塞等待时间(负数表示没有限制)
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 5
        # 关闭超时时间
        shutdown-timeout: 100ms

  # Spring Cache配置
  cache:
    type: redis
    # 缓存名称（预定义的缓存空间）
    cache-names: user,userList,file,fileList,hotData,statistics
    redis:
      # 全局缓存过期时间(毫秒) - 30分钟
      time-to-live: 1800000
      # 是否缓存空值,防止缓存穿透
      cache-null-values: false
      # Key前缀
      key-prefix: "cache:"
      # 是否使用前缀
      use-key-prefix: true

# 自定义缓存配置
cache:
  # 热点数据阈值（访问次数超过此值视为热点数据）
  hot-data-threshold: 10
  # 热点数据统计时间窗口（秒）
  hot-data-window: 60
  # 不同类型缓存的过期时间（秒）
  ttl:
    default: 3600      # 默认1小时
    user: 7200         # 用户缓存2小时
    file: 1800         # 文件缓存30分钟
    list: 600          # 列表缓存10分钟

# 注意:
# 1. Spring Boot 2.x+ 使用 spring.data.redis 而不是 spring.redis
# 2. 如果Redis有密码,取消password的注释并填写密码
# 3. 生产环境建议使用Redis哨兵或集群模式
# 4. 可以根据实际情况调整连接池大小
# 5. 日志配置已合并到主配置文件 application.yml